// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AXRole } from "./AXRole";
import type { AXValue } from "./AXValue";
import type { Bounds } from "./Bounds";
import type { ElementId } from "./ElementId";

/**
 * The unified element type - stored in registry and returned from API.
 * Flat structure: children are IDs, not nested. Trees derived client-side.
 */
export type AXElement = { id: ElementId, window_id: string, 
/**
 * null = no parent (root element)
 */
parent_id: ElementId | null, 
/**
 * null = children not yet discovered, [] = no children
 */
children_ids: Array<ElementId> | null, role: AXRole, subrole: string | null, label: string | null, value: AXValue | null, description: string | null, placeholder: string | null, bounds: Bounds | null, focused: boolean | null, enabled: boolean | null, };
