// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AXValue = { "type": "String", "value": string } | { "type": "Integer", "value": bigint } | { "type": "Float", "value": number } | { "type": "Boolean", "value": boolean };
