// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AXNode } from "./AXNode";

/**
 * A window with its accessibility tree root
 *
 * Combines OS window metadata with the accessibility tree.
 * The root is populated asynchronously after window discovery.
 */
export type AXWindow = { id: string, title: string, app_name: string, x: number, y: number, w: number, h: number, focused: boolean, process_id: number, root: AXNode | null, };
