// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * Window info from x-win. Root element ID populated from WindowRoot event.
 */
export type AXWindow = { id: string, title: string, app_name: string, x: number, y: number, w: number, h: number, focused: boolean, process_id: number, 
/**
 * Root element ID (client looks up from element registry)
 */
root_element_id: ElementId | null, };
