// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementId } from "./ElementId";

/**
 * Window info from x-win + accessibility.
 */
export type AXWindow = { id: string, title: string, app_name: string, x: number, y: number, w: number, h: number, focused: boolean, process_id: number, 
/**
 * Top-level element IDs. null = not yet discovered, [] = empty
 */
children: Array<ElementId> | null, };
