// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for an accessibility element
 *
 * Wraps a UUID string. Using a newtype prevents accidentally passing
 * a WindowId where an ElementId is expected.
 */
export type ElementId = string;
