// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AXValue } from "./AXValue";

/**
 * Update event for an element (broadcast when changes are observed)
 */
export type ElementUpdate = { "update_type": "ValueChanged", element_id: string, value: AXValue, } | { "update_type": "LabelChanged", element_id: string, label: string, } | { "update_type": "ElementDestroyed", element_id: string, };
