// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AXNode } from "./AXNode";
import type { AXWindow } from "./AXWindow";
import type { ElementUpdate } from "./ElementUpdate";

/**
 * Server-sent events (WebSocket)
 */
export type ServerEvent = { "event": "window_update", "data": Array<AXWindow> } | { "event": "window_root", "data": { window_id: string, root: AXNode, } } | { "event": "mouse_position", "data": { x: number, y: number, } } | { "event": "element_update", "data": ElementUpdate };
