// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AXElement } from "./AXElement";
import type { AXWindow } from "./AXWindow";
import type { ElementId } from "./ElementId";

export type ServerEvent = { "event": "window_update", "data": Array<AXWindow> } | { "event": "elements", "data": Array<AXElement> } | { "event": "element_destroyed", "data": { element_id: ElementId, } } | { "event": "mouse_position", "data": { x: number, y: number, } };
